// System-wide booking policies and rules constants (client-safe)
export const POLICIES = {
  // Booking limits
  MAX_ACTIVE_FACILITIES: 2,
  MAX_ACTIVE_ROOMS: 1,

  MAX_SPORTS_EQUIPMENT_ITEMS_PER_BOOKING: 3,
  MAX_LAB_EQUIPMENT_ITEMS_PER_BOOKING: 1,

  // Daily limits (per type - more granular control)
  MAX_FACILITY_BOOKINGS_PER_DAY: 3,
  MAX_ROOM_BOOKINGS_PER_DAY: 2,
  MAX_EQUIPMENT_BOOKINGS_PER_DAY: 5,
  MAX_LIBRARY_BOOKINGS_PER_DAY: 1,
  MAX_TOTAL_ACTIVE_BOOKINGS: 3,

  // Monthly limits (hours)
  MAX_FACILITY_HOURS_PER_MONTH: 15,
  MAX_ROOM_HOURS_PER_MONTH: 8,
  MAX_EQUIPMENT_BORROWS_PER_MONTH: 20,

  // Consecutive booking prevention
  MIN_GAP_BETWEEN_BOOKINGS_MINUTES: 0,
  MAX_CONSECUTIVE_SLOTS: 2,

  // Dynamic slot booking constraints (global defaults)
  MIN_BOOKING_DURATION_MINUTES: 15,
  MAX_BOOKING_DURATION_MINUTES: 120,
  WORKING_HOURS_START: 8, // 8 AM IST
  WORKING_HOURS_END: 20,  // 8 PM IST

  // Per-type duration defaults: Facilities
  MIN_DURATION_FACILITY: 15,
  MAX_DURATION_FACILITY: 120,
  HOURS_START_FACILITY: 8,
  HOURS_END_FACILITY: 20,

  // Per-type duration defaults: Rooms
  MIN_DURATION_ROOM: 15,
  MAX_DURATION_ROOM: 120,
  HOURS_START_ROOM: 8,
  HOURS_END_ROOM: 20,

  // Per-type duration defaults: Sports Equipment
  MIN_DURATION_SPORTS: 15,
  MAX_DURATION_SPORTS: 120,
  HOURS_START_SPORTS: 8,
  HOURS_END_SPORTS: 20,

  // Per-type duration defaults: Lab Equipment
  MIN_DURATION_LAB: 60,
  MAX_DURATION_LAB: 10080,
  HOURS_START_LAB: 8,
  HOURS_END_LAB: 20,

  // Cancellation limits
  LATE_CANCELLATION_HOURS: 24,

  // Advance booking window
  ADVANCE_BOOKING_DAYS: 7,

  // Slot durations (minutes)
  FACILITY_SLOT_MINUTES: 60,
  ROOM_SLOT_MINUTES: 60,
  SPORTS_EQUIPMENT_BORROW_MINUTES: 120,
  LAB_EQUIPMENT_BORROW_MINUTES: 10080,
  LIBRARY_BOOK_BORROW_MINUTES: 20160,

  // Equipment extension rules
  MAX_EQUIPMENT_EXTENSION_MINUTES: 60,
  MAX_EXTENSIONS_PER_BOOKING: 1,

  // Auto-cancel timings
  NO_SHOW_GRACE_MINUTES: 30,

  // QR validity windows (minutes)
  QR_VALIDITY_BEFORE_START: 15,
  QR_VALIDITY_AFTER_START: 30,
  QR_EQUIPMENT_PICKUP_WINDOW: 10,

  // Reschedule policies
  MAX_RESCHEDULE_PER_BOOKING: 1,
  MAX_RESCHEDULE_PER_MONTH: 3,
  RESCHEDULE_PENALTY_POINTS: 0,
  RESCHEDULE_BLOCK_WINDOW_HOURS: 2,

  // Penalties (4x multiplier)
  PENALTY_NO_SHOW: 4,
  PENALTY_LATE_RETURN: 4,
  PENALTY_DAMAGE: 8,
  PENALTY_CANCELLATION: 0,
  PENALTY_LATE_CANCELLATION: 2,
  PENALTY_BOOK_LATE_RETURN: 8,
  PENALTY_BOOK_NO_PICKUP: 2,

  // Escalating penalty system
  PENALTY_THRESHOLD_LEVEL_0: 20,
  PENALTY_THRESHOLD_LEVEL_1: 10,
  PENALTY_THRESHOLD_LEVEL_2: 10,
  SUSPENSION_DURATION_LEVEL_0: 7,
  SUSPENSION_DURATION_LEVEL_1: 10,
  SUSPENSION_DAYS: 7,

  // Special rules
  SHARED_TURF_GROUP_ID: 'TURF-1',
  LAB_EQUIPMENT_REQUIRES_APPROVAL: true,

  // Library rules
  MAX_BOOKS_PER_STUDENT: 1,
  LIBRARY_BOOK_PICKUP_WINDOW_HOURS: 24,

  // Group booking rules
  GROUP_BOOKING_MIN_MEMBERS: 6,
  GROUP_BOOKING_MIN_REPLY_TIME_HOURS: 10 / 60,
  GROUP_BOOKING_FINALIZATION_CUTOFF_HOURS: 5 / 60,
  GROUP_BOOKING_REPLY_TIME_MINUTES: 10,
  GROUP_BOOKING_CUTOFF_MINUTES: 5,
  GROUP_BOOKING_TEAM_SPORTS: ['Main Turf', 'Basketball Court', 'Volleyball Court'],
  ROOM_BOOKING_MIN_LEAD_MINUTES: 30,
} as const;
